# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUsecaseedit():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_usecaseedit(self):
    self.driver.get("http://localhost:8080/repo/use-cases/example-use-case")
    self.driver.find_element(By.CSS_SELECTOR, "#contentview-edit span:nth-child(2)").click()
    self.driver.find_element(By.ID, "form-widgets-IBasic-title").click()
    self.driver.find_element(By.ID, "form-widgets-IBasic-title").send_keys("Changed example use case")
    self.driver.find_element(By.ID, "form-buttons-save").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".portalMessage").text == "Info Changes saved"
    assert self.driver.find_element(By.CSS_SELECTOR, ".documentFirstHeading").text == "Changed example use case"
  
