# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTooledit():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_tooledit(self):
    self.driver.get("http://localhost:8080/repo/tools/example-tool-2/view")
    self.driver.find_element(By.CSS_SELECTOR, "#contentview-edit span:nth-child(2)").click()
    self.driver.find_element(By.ID, "form-widgets-IDublinCore-title").click()
    self.driver.find_element(By.ID, "form-widgets-IDublinCore-title").send_keys("Edited example tool")
    self.driver.find_element(By.ID, "form-buttons-save").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".documentFirstHeading").text == "Edited example tool"

