# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditmethod():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_editmethod(self):
    self.driver.get("http://localhost:8080/repo/method/example-method-9")
    self.driver.find_element(By.CSS_SELECTOR, "#contentview-edit span:nth-child(2)").click()
    self.driver.find_element(By.ID, "form-widgets-IBasic-title").click()
    element = self.driver.find_element(By.ID, "form-widgets-IBasic-title")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "form-widgets-IBasic-title").click()
    self.driver.find_element(By.ID, "form-widgets-IBasic-title").send_keys("Changed title")
    self.driver.find_element(By.ID, "form-buttons-save").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".documentFirstHeading").text == "Changed method title"

