# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestVisibilitysetprivate():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_visibilitysetprivate(self):
    self.driver.get("http://localhost:8080/repo/method/test")
    self.driver.find_element(By.CSS_SELECTOR, ".plone-toolbar-title:nth-child(1)").click()
    self.driver.find_element(By.ID, "workflow-transition-reject").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".portalMessage").text == "Info Item state changed."
    assert self.driver.find_element(By.CSS_SELECTOR, ".plone-toolbar-title:nth-child(1)").text == "State: Private"
    assert self.driver.find_element(By.CSS_SELECTOR, ".state-private:nth-child(2)").text == "State: Private"
  
